/**
 * Downloads the bundled symbol set from ARASAAC into the repository.
 *
 *   npm run symbols:fetch
 *
 * Resolves every term in lib/vocabulary.ts, plus every picture keyword used by
 * the shipped templates, to an ARASAAC pictogram; writes the PNGs into
 * public/symbols/ and an index into lib/symbols.generated.json.
 *
 * This is run by hand, not by CI, and its output is committed. That is the
 * point: the app must not depend on ARASAAC being reachable at runtime, and a
 * story must not lose its pictures because upstream reorganised its library.
 * Re-run it to add vocabulary; existing files are left alone unless --force.
 *
 * The images are ARASAAC pictograms (author Sergio Palao, origin ARASAAC,
 * owner Government of Aragón) under CC BY-NC-SA, which permits redistribution
 * with attribution, under the same licence, for non-commercial use.
 */
import { mkdir, writeFile, access, readFile } from "node:fs/promises";
import { join } from "node:path";
import { TEMPLATES } from "../lib/catalog";
import { VOCABULARY_TERMS } from "../lib/vocabulary";

const OUT_DIR = join(process.cwd(), "public", "symbols");
const INDEX_FILE = join(process.cwd(), "lib", "symbols.generated.json");
const force = process.argv.includes("--force");

/** id -> the terms that should find it. */
type Index = Record<string, { id: number; terms: string[] }>;

const terms = [
  ...new Set([
    ...VOCABULARY_TERMS,
    ...TEMPLATES.flatMap((t) => [t.cover, ...t.steps.map((s) => s.picture)]),
  ]),
].sort();

console.log(`Resolving ${terms.length} terms…`);

await mkdir(OUT_DIR, { recursive: true });

const existing: Index = await readFile(INDEX_FILE, "utf8")
  .then((s) => JSON.parse(s) as Index)
  .catch(() => ({}));

const index: Index = force ? {} : { ...existing };
const byId = new Map<number, Set<string>>();
for (const entry of Object.values(index)) {
  byId.set(entry.id, new Set(entry.terms));
}

let resolved = 0;
let downloaded = 0;
const unresolved: string[] = [];

for (const term of terms) {
  if (!force && index[term]) {
    resolved++;
    continue;
  }
  const id = await resolve(term);
  if (id === null) {
    unresolved.push(term);
    continue;
  }
  index[term] = { id, terms: [term] };
  byId.set(id, (byId.get(id) ?? new Set()).add(term));
  resolved++;

  const file = join(OUT_DIR, `${id}.png`);
  if (force || !(await exists(file))) {
    const bytes = await download(id);
    if (bytes) {
      await writeFile(file, bytes);
      downloaded++;
      process.stdout.write(".");
    }
  }
}

// Fold synonyms together so the index says which terms reach each picture.
for (const [term, entry] of Object.entries(index)) {
  entry.terms = [...(byId.get(entry.id) ?? new Set([term]))].sort();
}

await writeFile(INDEX_FILE, `${JSON.stringify(index, null, 2)}\n`, "utf8");

await writeFile(
  join(OUT_DIR, "LICENSE.txt"),
  `The PNG files in this directory are pictograms from ARASAAC.

  Author:  Sergio Palao
  Origin:  ARASAAC (https://arasaac.org)
  Owner:   Government of Aragón (Spain)
  Licence: Creative Commons BY-NC-SA
           https://creativecommons.org/licenses/by-nc-sa/4.0/

They are redistributed here under those terms. Any work derived from them must
carry the same licence and the same attribution, and must not be used
commercially. If you need a commercially usable symbol set, see
catalog/README.md for alternatives.

These files are generated by web/scripts/fetch-symbols.mts. Do not edit them by
hand.
`,
  "utf8",
);

console.log(
  `\n\n${resolved}/${terms.length} terms resolved, ${downloaded} images downloaded.`,
);
if (unresolved.length > 0) {
  console.warn(`No pictogram found for: ${unresolved.join(", ")}`);
}

async function resolve(term: string): Promise<number | null> {
  try {
    const res = await fetch(
      `https://api.arasaac.org/api/pictograms/en/search/${encodeURIComponent(term)}`,
      { headers: { Accept: "application/json" } },
    );
    if (!res.ok) return null;
    const hits = (await res.json()) as Array<{ _id: number }>;
    return Array.isArray(hits) && hits.length > 0 ? hits[0]._id : null;
  } catch {
    return null;
  }
}

async function download(id: number): Promise<Buffer | null> {
  try {
    // 300px is plenty: play mode scales to fit and these are flat line art.
    const res = await fetch(
      `https://static.arasaac.org/pictograms/${id}/${id}_300.png`,
    );
    if (!res.ok) return null;
    return Buffer.from(await res.arrayBuffer());
  } catch {
    return null;
  }
}

async function exists(path: string) {
  return access(path).then(
    () => true,
    () => false,
  );
}
